/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Spells } from "./Spells";
export type { Wizards } from "./Wizards";

export { Spells__factory } from "./factories/Spells__factory";
export { Wizards__factory } from "./factories/Wizards__factory";
